version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat_api_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=development
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST= db
    volumes:
      - "app-storage:/rails/storage"
volumes:
  mysql_data:
  app-storage:
